import { Inter } from "next/font/google";
import { StateContext } from "../context/stateContext";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StateContext>
        <body className={inter.className}>{children}</body>
      </StateContext>
    </html>
  );
}
